name: CI - Linting

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest  # Runner name
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: linting
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .