name: CD - Deploy in GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ["CI - Linting"]
    types:
      - completed
    conclusion:
      - success

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  pages:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Push in GitHub Pages
        uses: peaceiris/actions-gh-pages@v3

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

  webserver:
    runs-on: self-hosted
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Push to the prod server
        run: |
          sudo cp -r . /var/www/html
