name: CD - Deploy on prod webserver

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ["CI - Linting"]
    types:
      - completed

jobs:
  prod-2:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Push to the prod server
        run: |
          sudo cp -r . /var/www/html
